name: CI

on: [push, pull_request]

jobs:
    code_integration:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: Check format
              run: yarn check-format

            - name: Check lint
              run: yarn check-lint

            # - name: Run unit and integration tests
            #   run: yarn test:nw

            - name: Check production build
              run: yarn build
